### ISSUE TITLE
Issue with breadcrumb

### ISSUE THREAD

**Issue by JbIPS** [silexlabs/CloudExplorer2#22]
Maybe it's a personal opinion but I think when you click on a breadcrumb you should `cd` in this directory, not in its parent as it is today.

**Comment by lexoyo** [comment]
It is the case: when I am here in /tmp/aaa/bbb/...
![screenshot from 2017-11-14 12-28-38](https://user-images.githubusercontent.com/715377/32777675-686d9ffa-c937-11e7-8d9c-982655978e95.png)

...and I click on aaa, then I cd in /tmp/aaa/ 
![screenshot from 2017-11-14 12-28-46](https://user-images.githubusercontent.com/715377/32777703-7e203ec0-c937-11e7-9254-2e041aaf8166.png)

**Comment by JbIPS** [comment]
I'm sorry, that means only my fork is messed up 😅
