### ISSUE TITLE
Waiting for Google drive compatibility 

### ISSUE THREAD

**Issue by nk932714** [silexlabs/CloudExplorer2#24]

**Comment by JbIPS** [comment]
Hello @nk932714! Thank you for your input. I moved this issue to https://github.com/silexlabs/unifile/issues/124 since CloudExplorer only uses Unifile server to connect to the cloud. 
You're welcome to provide any help to speed up the process on the Unifile project 😸

**Comment by lexoyo** [comment]
Since it is now in the hands of the unifile contributors, I will close this issue

**Comment by nk932714** [comment]
Thnaks for your reply buddy
