### ISSUE TITLE
Assynchronous request

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/CloudExplorer2#26]
This is an assynchronous request which should be synchronous
https://github.com/silexlabs/CloudExplorer2/blob/master/src/js/UnifileService.js#L168

**Comment by JbIPS** [comment]
I thimk you mean the other way around 😉

**Comment by lexoyo** [comment]
Long day, long week.. no comment :)

**Comment by lexoyo** [comment]
I believe you fixed that @JbIPS

**Comment by JbIPS** [comment]
Yes I did! Thank you for closing it
