### ISSUE TITLE
FTP password is submitted in GET

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/CloudExplorer2#35]
When the user logs in to FTP or SFTP, the auth page sends the password in get to cloud explorer's router

We should avoid that and use POST data

**Comment by SouroucheB** [comment]
Could you try the #33 PR please and tell me if the problem still occures ? Because since I redirect the user to a all new URL in case of error, the get parameters no longer appears on my side.

**Comment by lexoyo** [comment]
I believe you did not change this: https://github.com/silexlabs/CloudExplorer2/blob/master/dist/login/ftp_login.html#L10
So ti will still be the cas
