### ISSUE TITLE
DROPBOX DONT WORK

### ISSUE THREAD

**Issue by starvecraft** [silexlabs/CloudExplorer2#37]
😨

**Comment by JbIPS** [comment]
Hello @starvecraft!

Could you be a little more precise: 
* Which version are you using?
* What's your OS?
* What are you trying to do?
* What was the result? Please include all the info you could gather (error message, HTTP call status, debug info)

**Comment by lexoyo** [comment]
I close this issue, feel free to reopen it @starvecraft
