### ISSUE TITLE
Warning message from React

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/CloudExplorer2#40]
At runtime I have this warning message: 
```
"Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs"
```
![screenshot from 2018-01-13 20-30-00](https://user-images.githubusercontent.com/715377/34909409-8e1e9a7c-f8a0-11e7-8403-7ad68a0711ba.png)

**Comment by JbIPS** [comment]
Looks like a [Prodotype](https://github.com/silexlabs/Prodotype) issue. I replaced all the `PropTypes` access in CE last time with the dedicated module. The same should be done in Prodotype.

**Comment by lexoyo** [comment]
Oh yes right, thank you :)
