### ISSUE TITLE
Do not re-auth when the user is already logged in

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/CloudExplorer2#49]
When I have already authorized access to a service, and I enter this service again, CE2 opens a popup for me to authorize again. This should not be the case

What I do
* open CE2
* double click on github
* authorize access to my github
* click the little "house" to go back to "/"
* [optional] close CE2 window and come back later
* double click on github again

What happens: a popup opens and goes to github, then github redirects to the callback page which closes the popup

What I expect: do not open a popup, enter github folder immediately

Also when the service is FS, the user is always logged in so we should not open a popup and close it when "/authorize" returns an empty URL

To do that, I am supposed to 
* use the code of this PR so that "/services" route will return a list of services with the "isLoggedIn" field
* when CE2 is initialized, I need to always load "/services", not just when we have an initial route set to "/"
* store the services in UnifileService class, do not cache it
* when the user wants to access a service, check UnifileService::services and see if isLoggedIn is true, in which case it will not open a popup
* when the user authorizes us to access a service, update UnifileService::services with isLoggedIn set to true
* when the an access error occures, update UnifileService::services with isLoggedIn set to false

**Comment by JbIPS** [comment]
Totally agree with you, it's particularly painful for services that needs your password.

But to add this feature we need to think about logout and switching/multiple accounts because we won't be able to do so if the login form disappear.

**Comment by lexoyo** [comment]
fixed by #68
