### ISSUE TITLE
FTP can crash the server

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/CloudExplorer2#57]
When I login with FTP on an unreachable server, it crashes the nodejs app

For example, on an instance which is online, host set as localhost
![screenshot from 2018-03-21 18-47-06](https://user-images.githubusercontent.com/715377/37727542-65407a4a-2d38-11e8-8558-f86c63b1545d.png)
Then
![screenshot from 2018-03-21 18-50-27](https://user-images.githubusercontent.com/715377/37727672-c0912ff2-2d38-11e8-9b3c-efedd11f7fc1.png)

**Comment by JbIPS** [comment]
There is currently an [issue with the FTP library](https://github.com/sergi/jsftp/issues/253) Unifile is using.

I'll try to find a fix or at least a safeguard for Unifile

**Comment by JbIPS** [comment]
A workaround has been applied in [Unifile 2.0.3](https://github.com/silexlabs/unifile/releases/tag/v2.0.3)
