### ISSUE TITLE
Single service mode

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/CloudExplorer2#62]
In some cases we need to have only 1 service and skip the list of services. For example the downloadable/offline version of Silex needs only the FS service. Another use case is a hosting company willing to host files only on their servers.

So there are a few things to do
* when the list of services is displayed, if there is only one service, open this service
* when the user is trying to list a folder and he is not authenticated, display a popin with the links 
  * log in => call the authenticate route and open a popup for oauth
  * register => open an external link
  * back to "/" => cd /
* hide the service from the bread crumbs
* optional idea: even if there is multiple services, allow the calling app to specify a "root path" and skip the services list, and sandbox the user to this folder, e.g. `/github/myrepo/gh-pages/` or `/ftp/htdocs/`

**Comment by lexoyo** [comment]
I've made a simplified version of this
https://github.com/silexlabs/CloudExplorer2/pull/68

This looks good to me event if it is not as good as the initial idea
* service name still appears in the breadcrumbs
* when user is not logged in it will display the single service, the user can click and follow the normal auth
* there is no register mechanism, but is can be added in the login popup

**Comment by godzone** [comment]
Its 7:30am here on Saturday morning so I have just seen this.  Will have a look at it shortly.
