### ISSUE TITLE
Multiple upload

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/CloudExplorer2#64]
When I upload more than 1 image at once, the images are corrupted
I tried
* on firefox
* 2 and 3 images
* with the OS file explorer and with drop files in the browser
* github and dropbox

**Comment by JbIPS** [comment]
Do you know how it is different from Silex publishing (which is using batch for multiple files upload)?

**Comment by lexoyo** [comment]
I have no idea, could you take a look at UnifileService and tell me if something looks weired?
