### ISSUE TITLE
API link broken

### ISSUE THREAD

**Issue by jotakar** [silexlabs/CloudExplorer2#74]
The API link is broken

**Comment by JbIPS** [comment]
Could you be more specific? What do you mean by 'API link'?

**Comment by jotakar** [comment]
Of course, my hand is quicker than my mind ;)
https://github.com/silexlabs/CloudExplorer2/blob/master/src/js/App.js#L77
For now, the best way to know the API is to take a look at the App class which exposes all CE methods here.
