### ISSUE TITLE
Feature request: image thumbnails

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/CloudExplorer2#88]
In order to display image thumbnails, I will create a different view specific to images

This mode will be used when the API is called like this:

```
ce.openFile(['.jpg', '.jpeg', '.png', '.gif'])
.then(fileInfo => {
    ...
})
```
This means these tasks

* [x] new "mode" for images, with thumbnails list
* [x] new design
* [x] resize images on the fly

If anyone has ideas (design or code) please comment :)
cc @clemos @ceubri @suddenheroes

**Comment by lexoyo** [comment]
Good resources here in Silex issue
https://github.com/silexlabs/Silex/issues/780

**Comment by lexoyo** [comment]
After thinking about it I will make the resize feature a unifile plugin 
cc @JbIPS

**Comment by JbIPS** [comment]
:astonished: what? What would you like to do at the unifile level?

**Comment by lexoyo** [comment]
Thx for your answer @JbIPS 
I was thinking a resize plugin but I did it simply with a new route in CE2
So now I'm considering adding some kind of "search" method in the API, what do you think?

**Comment by lexoyo** [comment]
Here is the first shot I took at this feature:

![screenshot_20191024_103314](https://user-images.githubusercontent.com/715377/67491135-caaf2700-f64a-11e9-9433-277e22f733d8.png)

**Comment by JbIPS** [comment]
The simplest solution I see is a flat search like this:
* list all file in directory with Unifile
* filter the result in CE2 with a regex

That's not optimum in term of bandwidth and it cannot be recursive but I think it's fast and easy enough for the use cases you have.

**Comment by lexoyo** [comment]
I have added a "search" related issue to unifile [in the unifile repo here](https://github.com/silexlabs/unifile/issues/162)
