### ISSUE TITLE
webdav support?

### ISSUE THREAD

**Issue by working-name** [silexlabs/CloudExplorer2#92]
Hi, silly question: how do I get webdav enabled?

**Comment by JbIPS** [comment]
Hi,

You'll need to pass the WebDav configuration to the constructor. You can look at how  [Silex does it](https://github.com/silexlabs/Silex/blob/bbe62acedd6734875403d2c0025f127d6fb19d15/src/server/router/CloudExplorerRouter.ts)

**Comment by working-name** [comment]
Thank you!
