### ISSUE TITLE
Your Heroku example is now dead

### ISSUE THREAD

**Issue by pminiggio** [silexlabs/CloudExplorer2#93]
When i clicked "local" and tried deleting some files. It's actually deleting the files that are used to run the example. So now it's dead xD

**Comment by pminiggio** [comment]
![image](https://user-images.githubusercontent.com/35456349/71478368-7877b700-27ef-11ea-9d62-96e86d317c62.png)

**Comment by lexoyo** [comment]
You will be remembered as @pminiggio  the man who killed cloud explorer 😱 

More seriously it should reset soon 👍

**Comment by pminiggio** [comment]
Ahah :p

**Comment by lexoyo** [comment]
Are you using ce2?
We have very few feedback :)

**Comment by pminiggio** [comment]
No i'm not sorry. Was looking into différent file managers / uploader options.
Looking for a wp-media like
